# This Python script leverages the pandas library to aggregate and sum counts for lemmatized words from a CSV file. 
# The input CSV, generated by a previous lemmatization script, is read into a pandas DataFrame. 
# The script then groups the data by lemma, calculates the total count for each lemma, 
# and saves the aggregated results in a new CSV file. Users can easily customize input 
# and output file paths to adapt the script for different datasets.

import pandas as pd

csv_input = r'C:\Users\romas\Documents\Code\Telegram\Data\word_quantity_full_lemma.csv'
csv_output = r'C:\Users\romas\Documents\Code\Telegram\Data\word_quantity_full_lemma_count.csv'

# If not, you can create one using pd.DataFrame()
df = pd.read_csv(csv_input)

# Group by 'lemma' and sum the 'count_post' for each group
subtotal_df = df.groupby('lemma')['count_post'].sum().reset_index()
subtotal_df.to_csv(csv_output, index=False)
